/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import sistemavotação.Aluno;

/**
 *
 * @author esdraschaves
 */
public class areaAluno extends javax.swing.JFrame {
    
    private Aluno aluno = null;
    /**
     * Creates new form areaAluno
     */
    public areaAluno() {
        initComponents();
    }
    
    public areaAluno(Aluno a) {
        this.aluno = a;
        initComponents();
        
        this.setDisplayAluno(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        text_bemVindo1 = new javax.swing.JLabel();
        text_setNome = new javax.swing.JLabel();
        text_email = new javax.swing.JLabel();
        text_setEmail = new javax.swing.JLabel();
        text_numMat = new javax.swing.JLabel();
        text_setNumMat = new javax.swing.JLabel();
        text_curso = new javax.swing.JLabel();
        text_setCurso = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        button_sair = new javax.swing.JButton();
        tabbed_areaAluno = new javax.swing.JTabbedPane();
        aba_Visualizar = new javax.swing.JPanel();
        text_opcao = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        aba_Atualizar = new javax.swing.JPanel();
        aba_Excluir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1130, 640));
        setMinimumSize(new java.awt.Dimension(1130, 640));
        setPreferredSize(new java.awt.Dimension(1130, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        text_bemVindo1.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        text_bemVindo1.setForeground(new java.awt.Color(254, 247, 247));
        text_bemVindo1.setText("Bem-Vindo,");
        getContentPane().add(text_bemVindo1);
        text_bemVindo1.setBounds(60, 30, 120, 33);

        text_setNome.setFont(new java.awt.Font("Waree", 0, 16)); // NOI18N
        text_setNome.setForeground(new java.awt.Color(254, 247, 247));
        getContentPane().add(text_setNome);
        text_setNome.setBounds(10, 70, 210, 40);

        text_email.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        text_email.setForeground(new java.awt.Color(254, 247, 247));
        text_email.setText("E-mail:");
        getContentPane().add(text_email);
        text_email.setBounds(10, 160, 60, 30);

        text_setEmail.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        text_setEmail.setForeground(new java.awt.Color(254, 247, 247));
        getContentPane().add(text_setEmail);
        text_setEmail.setBounds(10, 190, 200, 30);

        text_numMat.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        text_numMat.setForeground(new java.awt.Color(254, 247, 247));
        text_numMat.setText("Número de Matrícula:");
        getContentPane().add(text_numMat);
        text_numMat.setBounds(10, 230, 172, 30);

        text_setNumMat.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        text_setNumMat.setForeground(new java.awt.Color(254, 247, 247));
        getContentPane().add(text_setNumMat);
        text_setNumMat.setBounds(10, 260, 160, 30);

        text_curso.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        text_curso.setForeground(new java.awt.Color(254, 247, 247));
        text_curso.setText("Curso:");
        getContentPane().add(text_curso);
        text_curso.setBounds(10, 300, 60, 30);

        text_setCurso.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        text_setCurso.setForeground(new java.awt.Color(254, 247, 247));
        getContentPane().add(text_setCurso);
        text_setCurso.setBounds(10, 330, 160, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 126, 190, 10);

        jSeparator1.setBackground(new java.awt.Color(143, 141, 141));
        jSeparator1.setForeground(new java.awt.Color(87, 82, 82));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(230, 30, 10, 610);

        button_sair.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        button_sair.setText("Sair");
        button_sair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sairActionPerformed(evt);
            }
        });
        getContentPane().add(button_sair);
        button_sair.setBounds(10, 590, 210, 35);

        text_opcao.setText("Escolha uma opção abaixo para visualizar ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Listar Formulários e Número de questões");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        jRadioButton5.setText("jRadioButton5");

        jRadioButton6.setText("jRadioButton6");

        jRadioButton7.setText("jRadioButton7");

        jRadioButton8.setText("jRadioButton8");

        jRadioButton9.setText("jRadioButton9");

        jRadioButton10.setText("jRadioButton10");

        javax.swing.GroupLayout aba_VisualizarLayout = new javax.swing.GroupLayout(aba_Visualizar);
        aba_Visualizar.setLayout(aba_VisualizarLayout);
        aba_VisualizarLayout.setHorizontalGroup(
            aba_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aba_VisualizarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(aba_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_opcao)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton3)
                    .addGroup(aba_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton4))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        aba_VisualizarLayout.setVerticalGroup(
            aba_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aba_VisualizarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(text_opcao)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton6)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton7)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton8)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton9)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton10)
                .addGap(48, 48, 48))
        );

        tabbed_areaAluno.addTab("Visualizar", aba_Visualizar);

        javax.swing.GroupLayout aba_AtualizarLayout = new javax.swing.GroupLayout(aba_Atualizar);
        aba_Atualizar.setLayout(aba_AtualizarLayout);
        aba_AtualizarLayout.setHorizontalGroup(
            aba_AtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        aba_AtualizarLayout.setVerticalGroup(
            aba_AtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        tabbed_areaAluno.addTab("Atualizar", aba_Atualizar);

        javax.swing.GroupLayout aba_ExcluirLayout = new javax.swing.GroupLayout(aba_Excluir);
        aba_Excluir.setLayout(aba_ExcluirLayout);
        aba_ExcluirLayout.setHorizontalGroup(
            aba_ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        aba_ExcluirLayout.setVerticalGroup(
            aba_ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        tabbed_areaAluno.addTab("Excluir", aba_Excluir);

        getContentPane().add(tabbed_areaAluno);
        tabbed_areaAluno.setBounds(280, 60, 820, 540);

        jLabel1.setForeground(new java.awt.Color(132, 132, 132));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12107952-1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1190, 690);

        setSize(new java.awt.Dimension(1140, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sairActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_button_sairActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    
    private void setDisplayAluno(Aluno a) {
        text_setNome.setText(a.getNome());
        text_setEmail.setText(a.getEmail_inst());
        text_setNumMat.setText(a.getNro_matricula());
        text_setCurso.setText(a.getCurso());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(areaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(areaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(areaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(areaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new areaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aba_Atualizar;
    private javax.swing.JPanel aba_Excluir;
    private javax.swing.JPanel aba_Visualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane tabbed_areaAluno;
    private javax.swing.JLabel text_bemVindo1;
    private javax.swing.JLabel text_curso;
    private javax.swing.JLabel text_email;
    private javax.swing.JLabel text_numMat;
    private javax.swing.JLabel text_opcao;
    private javax.swing.JLabel text_setCurso;
    private javax.swing.JLabel text_setEmail;
    private javax.swing.JLabel text_setNome;
    private javax.swing.JLabel text_setNumMat;
    // End of variables declaration//GEN-END:variables
}
