/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classesdao.AlunoDao;
import classesdaoimpl.AlunoDaoImpl;
import java.sql.Date;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import sistemavotação.Aluno;
import uteis.Formatacao;

/**
 *
 * @author esdraschaves
 */
public class joinScreenAluno extends javax.swing.JFrame {
    
    Aluno pessoa = new Aluno();

    /**
     * Creates new form joinScreenAluno
     */
    public joinScreenAluno() {
        
    }

    joinScreenAluno(String cpf, String nome, String email_inst, String email_sec, Calendar data_nasc, String senha) {
        Date data = Formatacao.formataData(data_nasc);
        pessoa.setCPF(cpf);
        pessoa.setNome(nome);
        pessoa.setEmail_inst(email_inst);
        pessoa.setEmail_sec(email_sec);
        pessoa.setData_nasc(data);
        pessoa.setSenha(senha);
        pessoa.setTipo("alu");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_Curso = new javax.swing.JLabel();
        text_nroMatricula1 = new javax.swing.JLabel();
        input_nroMatricula = new javax.swing.JTextField();
        input_Curso = new javax.swing.JTextField();
        button_Confirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setPreferredSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(null);

        text_Curso.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        text_Curso.setForeground(new java.awt.Color(254, 254, 254));
        text_Curso.setText("Curso:");
        getContentPane().add(text_Curso);
        text_Curso.setBounds(30, 120, 60, 20);

        text_nroMatricula1.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        text_nroMatricula1.setForeground(new java.awt.Color(254, 254, 254));
        text_nroMatricula1.setText("Número de Matrícula:");
        getContentPane().add(text_nroMatricula1);
        text_nroMatricula1.setBounds(30, 50, 200, 20);

        input_nroMatricula.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_nroMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nroMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(input_nroMatricula);
        input_nroMatricula.setBounds(250, 50, 290, 28);

        input_Curso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(input_Curso);
        input_Curso.setBounds(250, 120, 290, 30);

        button_Confirmar.setText("Confirmar");
        button_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(button_Confirmar);
        button_Confirmar.setBounds(372, 290, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12107952-1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 380);

        setSize(new java.awt.Dimension(610, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_nroMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nroMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nroMatriculaActionPerformed
    

    
    private void button_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ConfirmarActionPerformed
        // TODO add your handling code here:
        pessoa.setCurso(input_Curso.getText());
        pessoa.setNro_matricula(input_nroMatricula.getText());
        AlunoDao aux = new AlunoDaoImpl();
        
        if(aux.insertAluno(pessoa) == 0){
            JOptionPane.showMessageDialog(null, "Erro!");
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Sucesso!");
            this.dispose();
        }
        
    }//GEN-LAST:event_button_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(joinScreenAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(joinScreenAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(joinScreenAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(joinScreenAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new joinScreenAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Confirmar;
    private javax.swing.JTextField input_Curso;
    private javax.swing.JTextField input_nroMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel text_Curso;
    private javax.swing.JLabel text_nroMatricula1;
    // End of variables declaration//GEN-END:variables
}
